version: '3.4'

services:
  light-eyes-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "80"
      - "8081"
    volumes:
#      - /Users/dcueto/docker-shared/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro # Mac path -> change user
#      - /Users/dcueto/docker-shared/ASP.NET/Https:/home/app/.aspnet/https:ro # Mac path -> change user
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro # windows path
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro # windows path
