version: '3.4'

networks:
  light-eyes-net:

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    platform: linux/amd64  # Specify platform
    environment:
      - ACCEPT_EULA=Y   # Accept the End-User License Agreement
      - POSTGRES_DB=webApi
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=LightEyesP@ssw0rd # Set the 'sa' user password
    ports:
      - "5432:5432"
    networks:
      - light-eyes-net
    volumes:
      - postgresql-container-data:/var/opt/mssql
  light-eyes-api:
    container_name: light-eyes-api
    image: ${DOCKER_REGISTRY-}light-eyes-api
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: light-eyes/Dockerfile
    depends_on:
      - postgresql
    networks:
      - light-eyes-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=postgresql;Database=webApi;Username=sa;Password=LightEyesP@ssw0rd;TrustServerCertificate=True

volumes:
  postgresql-container-data:
