version: '3.4'

networks:
  light-eyes-net:

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-container
    platform: linux/amd64  # Specify platform
    environment:
      - ACCEPT_EULA=Y   # Accept the End-User License Agreement
      - SA_PASSWORD=LightEyesP@ssw0rd # Set the 'sa' user password
      - MSSQL_PID=Express
    ports:
      - "8002:1433"
    networks:
      - light-eyes-net
    volumes:
      - sql-server-container-data:/var/opt/mssql
  light-eyes-api:
    container_name: light-eyes-api
    image: ${DOCKER_REGISTRY-}light-eyes-api
    ports:
      - "8001:80"
    build:
      context: .
      dockerfile: light-eyes/Dockerfile
    depends_on:
      - sql-server
    networks:
      - light-eyes-net

volumes:
  sql-server-container-data:
